name: Deploy Serverless Dementia API (Azure Functions)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCE_GROUP: rg-dementia
  AZURE_REGION: eastus
  DATABASE_NAME: dementia
  # Optional: define this to skip auto-discovery
  # SQL_SERVER_FQDN: dementia-sql-dev.database.windows.net

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure resource group exists (idempotent)
        shell: bash
        run: |
          set -Eeuo pipefail
          if ! az group show --name "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1; then
            echo "Creating $AZURE_RESOURCE_GROUP in $AZURE_REGION..."
            az group create --name "$AZURE_RESOURCE_GROUP" --location "$AZURE_REGION" -o none
          else
            echo "Resource group $AZURE_RESOURCE_GROUP already exists."
          fi

      - name: Resolve SQL server FQDN (env or auto)
        id: fqdn
        shell: bash
        run: |
          set -Eeuo pipefail
          if [ -n "${SQL_SERVER_FQDN:-}" ]; then
            echo "Using provided SQL_SERVER_FQDN: $SQL_SERVER_FQDN"
            echo "fqdn=$SQL_SERVER_FQDN" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Try to auto-discover a single SQL server in the RG
          FQDN=$(az sql server list -g "$AZURE_RESOURCE_GROUP" --query "[0].fullyQualifiedDomainName" -o tsv)
          if [ -z "$FQDN" ] || [ "$FQDN" = "None" ]; then
            echo "No SQL server found in resource group $AZURE_RESOURCE_GROUP."
            echo "Set env.SQL_SERVER_FQDN or create the server first."
            exit 1
          fi
          echo "Discovered SQL server: $FQDN"
          echo "fqdn=$FQDN" >> "$GITHUB_OUTPUT"

      - name: Deploy infra (Bicep)
        shell: bash
        run: |
          set -Eeuo pipefail
          DEPLOYMENT_NAME=infra
          az deployment group create \
            -g "$AZURE_RESOURCE_GROUP" \
            -n "$DEPLOYMENT_NAME" \
            -f infrastructure/infra.bicep \
            -p apiKey="${{ secrets.API_KEY }}" \
               sqlServerFqdn="${{ steps.fqdn.outputs.fqdn }}" \
               sqlDatabase="${DATABASE_NAME}" \
            -o none

      - name: Get Function App name
        id: getname
        shell: bash
        run: |
          set -Eeuo pipefail
          DEPLOYMENT_NAME=infra
          NAME=$(az deployment group show \
            -g "$AZURE_RESOURCE_GROUP" \
            -n "$DEPLOYMENT_NAME" \
            --query "properties.outputs.functionAppName.value" -o tsv)
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Zip package
        shell: bash
        run: |
          set -Eeuo pipefail
          cd api
          zip -r ../function.zip .

      - name: Deploy to Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ steps.getname.outputs.name }}
          package: function.zip

      - name: Show URLs
        shell: bash
        run: |
          set -Eeuo pipefail
          DEPLOYMENT_NAME=infra
          URL=$(az deployment group show \
            -g "$AZURE_RESOURCE_GROUP" \
            -n "$DEPLOYMENT_NAME" \
            --query "properties.outputs.functionUrl.value" -o tsv)
          echo "Swagger UI: $URL/swagger"
          echo "Swagger JSON: $URL/swagger.json"
