name: Deploy Azure App Service (Express API)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

env:
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure resource group exists
        run: |
          az group create -n "$AZURE_RESOURCE_GROUP" -l "$AZURE_LOCATION"

      - name: Deploy infrastructure (Bicep)
        run: |
          az deployment group create \
            -g "$AZURE_RESOURCE_GROUP" \
            --template-file infra/main.bicep \
            --parameters name="$AZURE_WEBAPP_NAME" location="$AZURE_LOCATION"

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (api)
        working-directory: api
        run: npm install

      - name: Build deployment artifact (zip)
        working-directory: api
        run: zip -r ../app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: app.zip
